# Generated by Django 6.1 on 2026-09-02 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('truck_number', models.CharField(blank=True, max_length=50, null=True)),
                ('truck_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Accepted', 'Accepted'), ('In Transit', 'In Transit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bKash', 'bKash'), ('Nagad', 'Nagad'), ('Card', 'Card'), ('Cash', 'Cash')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
