# Generated by Django 6.1 on 2026-09-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='address',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='available',
        ),
        migrations.AddField(
            model_name='driver',
            name='truck_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Offline', 'Offline')], default='Offline', max_length=20),
        ),
    ]
