"use client";

import { Search } from "lucide-react";
import { useMemo, useState } from "react";
import { type BookingStatus, useBooking } from "@/context/BookingContext";

export default function AdminBookingsPage() {
  const { bookings, updateBookingStatus, isLoaded } = useBooking();
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("All");
  const filtered = useMemo(() => bookings.filter((b) => { const match = `${b.id} ${b.customerName} ${b.pickupLocation} ${b.deliveryLocation}`.toLowerCase().includes(query.toLowerCase()); return match && (filter === "All" || b.status === filter); }), [bookings, query, filter]);
  return <div className="mx-auto max-w-7xl"><p className="text-sm font-semibold text-orange-600">OPERATIONS</p><h1 className="mt-1 text-2xl font-bold text-slate-900 sm:text-3xl">Manage bookings</h1><p className="mt-1 text-sm text-slate-500">Review orders, update delivery progress and assign operations.</p><section className="mt-7 rounded-lg border border-slate-200 bg-white"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><div className="relative flex-1"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search booking, customer or route" className="w-full rounded-md border border-slate-200 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-orange-500" /></div><select value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-md border border-slate-200 bg-white px-3 text-sm font-medium text-slate-700">{["All", "Confirmed", "Driver Assigned", "Picked Up", "In Transit", "Delivered", "Cancelled"].map(s => <option key={s}>{s}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full min-w-220 text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Booking</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Route</th><th className="px-5 py-3">Truck</th><th className="px-5 py-3">Fare</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{!isLoaded ? <tr><td className="px-5 py-8 text-slate-500" colSpan={6}>Loading bookings...</td></tr> : filtered.length === 0 ? <tr><td className="px-5 py-12 text-center text-slate-500" colSpan={6}>No bookings match the current view.</td></tr> : filtered.map(b => <tr key={b.id} className="border-t border-slate-100"><td className="px-5 py-4 font-semibold text-slate-800">{b.id}<p className="mt-1 text-xs font-normal text-slate-400">{b.pickupDate} at {b.pickupTime}</p></td><td className="px-5 py-4 text-slate-700">{b.customerName}<p className="mt-1 text-xs text-slate-400">{b.phone}</p></td><td className="max-w-62 px-5 py-4 text-slate-600"><p className="truncate">{b.pickupLocation}</p><p className="mt-1 truncate text-xs text-slate-400">to {b.deliveryLocation}</p></td><td className="px-5 py-4 text-slate-600">{b.truckName}<p className="mt-1 text-xs text-slate-400">{b.truckCapacity}</p></td><td className="px-5 py-4 font-semibold text-slate-800">BDT {b.totalPrice.toLocaleString()}</td><td className="px-5 py-4"><select aria-label={`Update status for ${b.id}`} value={b.status} onChange={(e) => updateBookingStatus(b.id, e.target.value as BookingStatus)} className="rounded-md border border-slate-200 bg-white px-2 py-1.5 text-xs font-semibold text-slate-700">{["Confirmed", "Driver Assigned", "Picked Up", "In Transit", "Delivered", "Cancelled"].map(s => <option key={s}>{s}</option>)}</select></td></tr>)}</tbody></table></div></section></div>;
}
