"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { Banknote, ClipboardList, LayoutDashboard, Route, Truck, UserRound, X } from "lucide-react";

import { useAuth } from "@/context/AuthContext";

const links = [{ href: "/driver", label: "Dashboard", icon: LayoutDashboard }, { href: "/driver/assignments", label: "Assignments", icon: ClipboardList }, { href: "/driver/trips", label: "Trips", icon: Route }, { href: "/driver/earnings", label: "Earnings", icon: Banknote }, { href: "/driver/profile", label: "Profile", icon: UserRound }];
export default function DriverSidebar({ open, onClose }: { open: boolean; onClose: () => void }) { const pathname = usePathname(); const { user } = useAuth(); return <><div className={`fixed inset-0 z-40 bg-slate-950/40 transition lg:hidden ${open ? "opacity-100" : "pointer-events-none opacity-0"}`} onClick={onClose} /><aside className={`fixed inset-y-0 left-0 z-50 flex w-68 flex-col bg-slate-950 text-slate-300 transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="flex h-18 items-center justify-between border-b border-white/10 px-5"><Link href="/driver" onClick={onClose} className="flex items-center gap-3 text-lg font-bold text-white"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-orange-500"><Truck size={20} /></span>Truck<span className="text-orange-400">Lagbe</span></Link><button onClick={onClose} className="rounded-md p-2 lg:hidden" aria-label="Close menu"><X size={20} /></button></div><div className="px-5 py-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-500">Driver portal</p><div className="mt-3 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-orange-100 font-bold text-orange-700">{(user?.name ?? "Driver").charAt(0).toUpperCase()}</span><div><p className="text-sm font-semibold text-white">{user?.name ?? "Driver"}</p><p className="text-xs capitalize text-green-400">{user?.role ?? "driver"}</p></div></div></div><nav className="flex-1 border-t border-white/10 px-3 py-5">{links.map(({ href, label, icon: Icon }) => { const active = href === "/driver" ? pathname === href : pathname.startsWith(href); return <Link key={href} href={href} onClick={onClose} className={`mb-1 flex items-center gap-3 rounded-lg px-3 py-3 text-sm font-semibold transition ${active ? "bg-orange-500 text-white" : "hover:bg-white/8 hover:text-white"}`}><Icon size={19} />{label}</Link>; })}</nav><div className="border-t border-white/10 p-4 text-xs text-slate-500">Need assistance?<br /><span className="text-slate-300">Call support: 16345</span></div></aside></> }
